apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dotnet-0423
  janus-idp.io/tekton: dotnet-0423
  backstage.io/kubernetes-id: dotnet-0423
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dotnet-0423
resources:
- initialize-namespace.yaml
- deployment.yaml
- route.yaml
- service.yaml 
